{
 "title": "Monitoring Infrastructure",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nombre de conteneurs actifs ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Réseau entrant ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name!=\"\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Mémoire utilisée ",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name!=\"\"}[5m])*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_usage_bytes{name!=\"\"} / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{name!=\"\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(container_last_seen{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}